### ISSUE TITLE
Can't find the file DeepDTA_KIBA.tsv, or methods to prepare it.

### ISSUE THREAD

**Issue by aryan7781** [kalleknast/BindingAffinity#1]
https://github.com/kalleknast/BindingAffinity/blob/94984480a240cf76e6f6d0a011d8f61e1099d766/data.py#L307
Hello, could you help with the reference to **.tsv** files referenced in the code? The raw directory contains only pickle and json files.!

**Comment by kalleknast** [comment]
The file is too big (80 MB) to upload to GitHub.
Please download it The file is too big (80 MB) to upload to GitHub.
Please download it [here](https://drive.google.com/file/d/16TeMS21KlA84G5HSimBEpBfyQFzFrCU6/view?usp=sharing).

**Comment by aryan7781** [comment]
Thanks... helps a lot.😄😄
